version: '3.8'

services:
  db:
    image: mysql:5.7.32
    restart: unless-stopped
    container_name: app_db
    ports: 
        - $MYSQL_PORT:3306
    volumes:
        - ./volumes/mysql:/var/lib/mysql
    env_file:
      - ./envs/mysql.env
    user: "1000:1000"

  db_manager:
    depends_on:
        - db
    image: adminer:4.7.8-standalone
    restart: unless-stopped
    env_file:
        - ./envs/adminer.env
    ports:
        - $DB_MANAGER_PORT:8080
    container_name: db_manager
    links: 
        - db

  app:
    build: .
    image: $APP_IMAGE
    restart: unless-stopped
    container_name: app
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html
    env_file:
      - ./envs/app.env
  
  nginx:
    depends_on:
      - app
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - $NGINX_PORT:80
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html
      - $SERVER_SRC:/etc/nginx/conf.d/default.conf